#!/usr/bin/env python3
"""Regenerate a domain's catalog.md from note frontmatter.

Per the LLM Wiki requirements (R5) §5: catalog.md is auto-generated,
exhaustive, and never hand-edited. Run this after any Ingest that
adds/changes notes in a domain folder. Intended to be wired into the
nightly routine (§8), not run ad hoc by an agent mid-conversation.

`article` and `outlet` have hand-tuned columns (they predate the other
domains and carry schema-migration fallbacks). Every other domain under
`entities/` is handled generically: its column set is read straight out
of that domain's own `index.md` "YAML registry" table, so a brand-new
domain works the moment its index.md exists — no code change needed here.

catalog.md is always fully rewritten (open(..., "w")), so it does not
matter whether the file already exists: first run creates it, every
run after that replaces it wholesale.

Usage: python3 generate_catalog.py <domain>
  where <domain> is any entities/<domain>/ folder that has an index.md
"""
import sys
import glob
import re
import os
from datetime import datetime

try:
    import yaml
except ImportError:
    print("This script requires PyYAML. Install it with: pip3 install pyyaml", file=sys.stderr)
    sys.exit(2)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP_FILES = {"index.md", "catalog.md", "_template.md", "log.md"}


def parse_frontmatter(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    try:
        fm = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError as exc:
        raise ValueError(f"invalid YAML frontmatter in {path}: {exc}") from exc
    if not isinstance(fm, dict):
        raise ValueError(f"frontmatter in {path} must be a mapping")
    return fm


def scalar(value):
    """Stable catalog text for typed YAML values without losing list contents."""
    if value is None:
        return ""
    if isinstance(value, (list, tuple)):
        return ", ".join(str(item) for item in value)
    if hasattr(value, "isoformat") and not isinstance(value, str):
        return value.isoformat()
    return str(value)


def find_notes(domain_dir):
    paths = []
    for path in glob.glob(os.path.join(domain_dir, "**", "*.md"), recursive=True):
        if os.path.basename(path) in SKIP_FILES:
            continue
        paths.append(path)
    return sorted(paths)


def gen_article_catalog(domain_dir):
    rows = []
    for path in find_notes(domain_dir):
        fm = parse_frontmatter(path)
        rel = os.path.relpath(path, domain_dir)
        stem = os.path.basename(path)[:-3]
        note_id = scalar(fm.get("sourceId") or fm.get("articleId") or stem)
        slug = stem[len(note_id) + 1:] if stem.startswith(note_id + "-") else stem
        title = scalar(fm.get("articleTitle")) or slug.replace("-", " ").title()
        published = scalar(fm.get("publishedDate"))
        status = scalar(fm.get("status", "active"))
        source_type = scalar(fm.get("sourceType"))
        sentiment = scalar(fm.get("toneSentiment"))
        tags = scalar(fm.get("tags"))
        rows.append((published, note_id, title, status, source_type, sentiment, tags, rel))
    rows.sort(key=lambda r: r[0], reverse=True)

    lines = []
    lines.append("---")
    lines.append("type: domain-catalog")
    lines.append("domain: Sources")
    lines.append("subtype: article")
    lines.append(f"generated_at: {datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}")
    lines.append(f"note_count: {len(rows)}")
    lines.append("---")
    lines.append("")
    lines.append("# Catalog: Sources — Articles")
    lines.append("")
    lines.append("> **Auto-generated by `scripts/generate_catalog.py`. Never hand-edit — regenerated by the nightly routine (§8) whenever this domain's Ingest runs.**")
    lines.append("")
    lines.append(f"**Note count:** {len(rows)} | **Last generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")
    lines.append("| Published | ID | Title | Status | Source | Sentiment | Tags | File |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for published, note_id, title, status, source_type, sentiment, tags, rel in rows:
        title_e = title.replace("|", "\\|")
        lines.append(f"| {published} | {note_id} | {title_e} | {status} | {source_type} | {sentiment} | {tags} | [{rel}]({rel}) |")
    return "\n".join(lines) + "\n"


def gen_outlet_catalog(domain_dir):
    rows = []
    for path in find_notes(domain_dir):
        fm = parse_frontmatter(path)
        rel = os.path.relpath(path, domain_dir)
        outlet_id = fm.get("outletId", os.path.basename(path)[:-3])
        rows.append((
            scalar(fm.get("displayName", outlet_id)),
            scalar(outlet_id),
            scalar(fm.get("country")),
            scalar(fm.get("mediaCategory")),
            scalar(fm.get("articleCount", "0")),
            scalar(fm.get("aliases")),
            rel,
        ))
    rows.sort(key=lambda r: r[0].lower())

    lines = []
    lines.append("---")
    lines.append("type: domain-catalog")
    lines.append("domain: Outlets")
    lines.append("subtype: outlet")
    lines.append(f"generated_at: {datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}")
    lines.append(f"note_count: {len(rows)}")
    lines.append("---")
    lines.append("")
    lines.append("# Catalog: Outlets")
    lines.append("")
    lines.append("> **Auto-generated by `scripts/generate_catalog.py`. Never hand-edit — regenerated by the nightly routine (§8) whenever this domain's Ingest runs.**")
    lines.append("")
    lines.append(f"**Note count:** {len(rows)} | **Last generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")
    lines.append("| Outlet | ID | Country | Media Category | Article Count | Aliases | File |")
    lines.append("|---|---|---|---|---|---|---|")
    for display, outlet_id, country, category, count, aliases, rel in rows:
        display_e = display.replace("|", "\\|")
        lines.append(f"| {display_e} | {outlet_id} | {country} | {category} | {count} | {aliases} | [{rel}]({rel}) |")
    return "\n".join(lines) + "\n"


def parse_registry_fields(index_md_path):
    """Pull the ordered field list out of a domain index.md's "YAML registry" table."""
    if not os.path.exists(index_md_path):
        return []
    with open(index_md_path, encoding="utf-8") as f:
        lines = f.read().splitlines()
    fields = []
    in_table = False
    for line in lines:
        stripped = line.strip()
        if not in_table:
            if stripped.startswith("| Field") and "Type" in stripped:
                in_table = True
            continue
        if not stripped.startswith("|"):
            break
        if re.match(r"^\|[\s:-]+\|", stripped):
            continue  # the |---|---|---| separator row
        cell = stripped.split("|")[1].strip().strip("`")
        if cell:
            fields.append(cell)
    return fields


def gen_generic_entity_catalog(domain, domain_dir):
    index_fm = parse_frontmatter(os.path.join(domain_dir, "index.md"))
    domain_label = index_fm.get("domain", domain.title())
    fields = parse_registry_fields(os.path.join(domain_dir, "index.md"))
    if not fields:
        fields = ["id"]  # degenerate fallback if a domain ships with no registry table yet
    title_field = "displayName" if "displayName" in fields else fields[0]

    rows = []
    for path in find_notes(domain_dir):
        fm = parse_frontmatter(path)
        rel = os.path.relpath(path, domain_dir)
        row = [scalar(fm.get(field)) for field in fields]
        sort_key = scalar(fm.get(title_field, os.path.basename(path)[:-3])).lower()
        rows.append((sort_key, row, rel))
    rows.sort(key=lambda r: r[0])

    lines = []
    lines.append("---")
    lines.append("type: domain-catalog")
    lines.append(f"domain: {domain_label}")
    lines.append(f"subtype: {index_fm.get('subtype', domain)}")
    lines.append(f"generated_at: {datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}")
    lines.append(f"note_count: {len(rows)}")
    lines.append("---")
    lines.append("")
    lines.append(f"# Catalog: {domain_label}")
    lines.append("")
    lines.append("> **Auto-generated by `scripts/generate_catalog.py`. Never hand-edit — regenerated by the nightly routine (§8) whenever this domain's Ingest runs.**")
    lines.append("")
    lines.append(f"**Note count:** {len(rows)} | **Last generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")
    header = fields + ["File"]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "---|" * len(header))
    for _, row, rel in rows:
        row_e = [str(v).replace("|", "\\|") for v in row]
        lines.append("| " + " | ".join(row_e) + f" | [{rel}]({rel}) |")
    if not rows:
        lines.append("")
        lines.append("*(no notes yet — this domain is populated by cascade, per its index.md)*")
    return "\n".join(lines) + "\n"


def main():
    entities_dir = os.path.join(ROOT, "entities")
    available = sorted(
        os.path.basename(os.path.dirname(p))
        for p in glob.glob(os.path.join(entities_dir, "*", "index.md"))
    )

    if len(sys.argv) != 2 or sys.argv[1] not in available:
        print(f"Usage: python3 generate_catalog.py <domain>", file=sys.stderr)
        print(f"Available domains (have an index.md): {', '.join(available)}", file=sys.stderr)
        sys.exit(1)

    domain = sys.argv[1]
    domain_dir = os.path.join(entities_dir, domain)
    out_path = os.path.join(domain_dir, "catalog.md")

    if domain == "article":
        content = gen_article_catalog(domain_dir)
    elif domain == "outlet":
        content = gen_outlet_catalog(domain_dir)
    else:
        content = gen_generic_entity_catalog(domain, domain_dir)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
